ignore_images: false

module_order:
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results after adapter trimming."
      path_filters:
        - "*_trimmed_R[12]_fastqc.zip"
  - cutadapt
  - fastp
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*_raw_R[12]_fastqc.zip"

custom_data:
  insert_size:
    section_name: "Insert size"
    file_format: "tsv"
    plot_type: "linegraph"
  coverage:
    section_name: "Coverage"
    file_format: "tsv"
    plot_type: "linegraph"
  sequencing_depth:
    section_name: "Sequencing depth"
    description: "Average sequencing depth computed as total number of bases in reads divided by total number of bases in reference contigs."
    file_format: "tsv"
    plot_type: "bargraph"
    pconfig:
      id: "custom_sequencing_depth"
      title: "Custom: Average Sequencing Depth"
      cpswitch: False
      use_legend: False
      tt_decimals: 2
      tt_suffix: " X coverage"
      tt_percentages: False
sp:
  insert_size:
    fn: "*_samtools-IS.txt"
  coverage:
    fn: "*_samtools-COV.txt"
  sequencing_depth:
    fn: "*_seq-depth.txt"
